name: Deploy static site to Beget

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP (lftp)
        env:
          BEGET_HOST: ${{ secrets.BEGET_HOST }}
          BEGET_USER: ${{ secrets.BEGET_USER }}
          BEGET_PASS: ${{ secrets.BEGET_PASS }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          lftp -e "
            set cmd:fail-exit true
            set net:max-retries 2
            set net:timeout 25
            set sftp:auto-confirm yes
            open -u ${BEGET_USER},${BEGET_PASS} -p 22 sftp://${BEGET_HOST}
            pwd
            cd ${REMOTE_DIR}
            mirror --reverse --delete --verbose \
                   --exclude-glob '.git*' \
                   --exclude 'README.md' \
                   . .
            bye
          "
          
          EOF

