name: Deploy static site to Beget

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via SFTP/FTPS
        env:
          BEGET_HOST: ${{ secrets.BEGET_HOST }}
          BEGET_USER: ${{ secrets.BEGET_USER }}
          BEGET_PASS: ${{ secrets.BEGET_PASS }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          # Зеркалим весь репозиторий (кроме служебного мусора) в public_html
          lftp -u "$BEGET_USER","$BEGET_PASS" "$BEGET_HOST" <<EOF
          set sftp:auto-confirm yes
          set ftp:ssl-force true
          set ssl:verify-certificate no
          cd $REMOTE_DIR
          mirror --reverse --delete --verbose \
                 --exclude-glob ".git*" \
                 --exclude "README.md" \
                 .
          bye
          EOF

