name: Deploy static site to Beget (FTPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# чтобы не висели одновременные запуски
concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.BEGET_HOST }}       # denisoko.beget.tech
          username: ${{ secrets.BEGET_USER }}
          password: ${{ secrets.BEGET_PASS }}
          protocol: ftps                          # явный TLS на 21 порту
          port: 21
          # что отправляем: '.' — весь репозиторий; поменяйте на 'dist' если есть сборка
          local-dir: .
          # куда на сервере: '/' — корень FTP-аккаунта (у вас это public_html)
          server-dir: ${{ secrets.REMOTE_DIR }}
          # список исключений (маски)
          exclude: |
            **/.git*
            **/.github/**
            **/.gitignore
            **/.ftp-deploy-sync-state.json
            **/node_modules/**
            **/.DS_Store
          # синхронизация: удалит на сервере файлы, которых нет локально
          dangerous-clean-slate: true
          # подробные логи
          log-level: verbose

